from definitions.terminology.attribute_values import InstanceComponent, Jurisdiction

MAP_INSTANCE = {
    "Sector kanton Rechtbank": InstanceComponent.RECHTBANK.value,
    "Kantongerecht": InstanceComponent.RECHTBANK.value,
    "'s Gravenhage": InstanceComponent.S_GRAVENHAGE.value,
    "Den Haag": InstanceComponent.S_GRAVENHAGE.value,
    "Alkmaar": InstanceComponent.NOORD_HOLLAND.value,
    "Almelo": InstanceComponent.OVERIJSSEL.value,
    "Alphen aan den Rijn": InstanceComponent.S_GRAVENHAGE.value,
    "Amersfoort": InstanceComponent.MIDDEN_NEDERLAND.value,
    "Apeldoorn": InstanceComponent.GELDERLAND.value,
    "Appingedam": InstanceComponent.NOORD_NEDERLAND.value,
    "Assen": InstanceComponent.NOORD_HOLLAND.value,
    "Beetsterzwaag": InstanceComponent.NOORD_NEDERLAND.value,
    "Bergen op Zoom": InstanceComponent.ZEELAND.value,
    "Bergum": InstanceComponent.NOORD_NEDERLAND.value,
    "Bolsward": InstanceComponent.NOORD_NEDERLAND.value,
    "Boxmeer": InstanceComponent.OOST_BRABANT.value,
    "Breda": InstanceComponent.ZEELAND.value,
    "Breukelen-Nijenrode": InstanceComponent.MIDDEN_NEDERLAND.value,
    "Brielle": InstanceComponent.ROTTERDAM.value,
    "Delft": InstanceComponent.S_GRAVENHAGE.value,
    "Den Helder": InstanceComponent.NOORD_HOLLAND.value,
    "Deventer": InstanceComponent.OVERIJSSEL.value,
    "Dordrecht": InstanceComponent.ROTTERDAM.value,
    "Eindhoven": InstanceComponent.OOST_BRABANT.value,
    "Elst": InstanceComponent.GELDERLAND.value,
    "Emmen": InstanceComponent.NOORD_NEDERLAND.value,
    "Enschede": InstanceComponent.OVERIJSSEL.value,
    "Geldermalsen": InstanceComponent.GELDERLAND.value,
    "Goes": InstanceComponent.ZEELAND.value,
    "Goor": InstanceComponent.OVERIJSSEL.value,
    "Gorinchem": InstanceComponent.ROTTERDAM.value,
    "Gouda": InstanceComponent.S_GRAVENHAGE.value,
    "Groenlo": InstanceComponent.GELDERLAND.value,
    "Groningen": InstanceComponent.NOORD_NEDERLAND.value,
    "Gulpen": InstanceComponent.LIMBURG.value,
    "Haarlem": InstanceComponent.NOORD_HOLLAND.value,
    "Haarlemmermeer": InstanceComponent.NOORD_HOLLAND.value,
    "Harderwijk": InstanceComponent.GELDERLAND.value,
    "Heerenveen": InstanceComponent.NOORD_NEDERLAND.value,
    "Heerlen": InstanceComponent.LIMBURG.value,
    "Helmond": InstanceComponent.OOST_BRABANT.value,
    "Hilversum": InstanceComponent.MIDDEN_NEDERLAND.value,
    "Hoofddorp": InstanceComponent.NOORD_HOLLAND.value,
    "Hoogeveen": InstanceComponent.NOORD_NEDERLAND.value,
    "Hoorn": InstanceComponent.NOORD_HOLLAND.value,
    "Kampen": InstanceComponent.NOORD_NEDERLAND.value,
    "Leiden": InstanceComponent.S_GRAVENHAGE.value,
    "Lelystad": InstanceComponent.MIDDEN_NEDERLAND.value,
    "Lemmer": InstanceComponent.NOORD_NEDERLAND.value,
    "Maastricht": InstanceComponent.LIMBURG.value,
    "Medemblik": InstanceComponent.NOORD_HOLLAND.value,
    "Meppel": InstanceComponent.NOORD_NEDERLAND.value,
    "Middelburg": InstanceComponent.ZEELAND.value,
    "Nijmegen": InstanceComponent.GELDERLAND.value,
    "Ommen": InstanceComponent.OVERIJSSEL.value,
    "Onderdendam": InstanceComponent.NOORD_NEDERLAND.value,
    "Oost-Nederland": InstanceComponent.GELDERLAND.value,
    "Oostburg": InstanceComponent.ZEELAND.value,
    "Oud-Beijerland": InstanceComponent.ROTTERDAM.value,
    "Purmerend": InstanceComponent.NOORD_HOLLAND.value,
    "Ridderkerk": InstanceComponent.ROTTERDAM.value,
    "Roermond": InstanceComponent.LIMBURG.value,
    "Schiedam": InstanceComponent.ROTTERDAM.value,
    "Schoonhoven": InstanceComponent.ROTTERDAM.value,
    "Sittard": InstanceComponent.LIMBURG.value,
    "Sliedrecht": InstanceComponent.ROTTERDAM.value,
    "Sneek": InstanceComponent.NOORD_NEDERLAND.value,
    "Sommelsdijk": InstanceComponent.ROTTERDAM.value,
    "Steenwijk": InstanceComponent.OVERIJSSEL.value,
    "Terborg": InstanceComponent.GELDERLAND.value,
    "Terneuzen": InstanceComponent.ZEELAND.value,
    "Tholen": InstanceComponent.ZEELAND.value,
    "Tiel": InstanceComponent.GELDERLAND.value,
    "Tilburg": InstanceComponent.ZEELAND.value,
    "Utrecht": InstanceComponent.MIDDEN_NEDERLAND.value,
    "Veendam": InstanceComponent.NOORD_NEDERLAND.value,
    "Venlo": InstanceComponent.LIMBURG.value,
    "Wageningen": InstanceComponent.GELDERLAND.value,
    "Weert": InstanceComponent.LIMBURG.value,
    "Winschoten": InstanceComponent.NOORD_NEDERLAND.value,
    "Woerden": InstanceComponent.MIDDEN_NEDERLAND.value,
    "Zaandam": InstanceComponent.NOORD_HOLLAND.value,
    "Zevenbergen": InstanceComponent.ZEELAND.value,
    "Zierikzee": InstanceComponent.ZEELAND.value,
    "Zuidbroek": InstanceComponent.NOORD_NEDERLAND.value,
    "Zutphen": InstanceComponent.GELDERLAND.value,
    "Zwolle": InstanceComponent.OVERIJSSEL.value,
    "Zwolle-Lelystad": InstanceComponent.OVERIJSSEL.value,
    f"{InstanceComponent.RECHTBANK.value} 's-Hertogenbosch": f"{InstanceComponent.RECHTBANK.value} {InstanceComponent.OOST_BRABANT.value}",
    f"{InstanceComponent.RECHTBANK.value} Arnhem": f"{InstanceComponent.RECHTBANK.value} {InstanceComponent.GELDERLAND.value}",
    f"{InstanceComponent.GERECHTSHOF.value} Arnhem": f"{InstanceComponent.GERECHTSHOF.value} {InstanceComponent.ARNHEM_LEEUWARDEN.value}",
    f"{InstanceComponent.RECHTBANK.value} Leeuwarden": f"{InstanceComponent.RECHTBANK.value} {InstanceComponent.NOORD_NEDERLAND.value}",
    f"{InstanceComponent.GERECHTSHOF.value} Leeuwarden": f"{InstanceComponent.GERECHTSHOF.value} {InstanceComponent.ARNHEM_LEEUWARDEN.value}",
    "Arnhem-Leeuwarden-Leeuwarden": InstanceComponent.ARNHEM_LEEUWARDEN.value,
}

MAP_JURISDICTION = {"NL": Jurisdiction.NL.value, "Nederland": Jurisdiction.NL.value}
