from os.path import dirname, abspath, join
"""
Purpose of script:
a)  define directory paths
b)  define the terminology to be used throughout all data processing steps.
    The original terms used in the raw data of "Rechtspraak" and "Legal intelligence" are mapped to each other
    and replaced by a global label.
    Variable names correspond to the original terms and are denoted with the prefix of their source
    (RS = Rechtspraak, LI = Legal intelligence).
"""

# PATH DEFINITIONS:
DIR_ROOT = dirname(abspath(__file__))
DIR_DATA = join(DIR_ROOT, 'data')
DIR_RECHTSPRAAK = join(DIR_DATA, 'OpenDataUitspraken')
CSV_RS_CASES = join(DIR_DATA, 'RS_cases.csv')
CSV_RS_OPINIONS = join(DIR_DATA, 'RS_case_opinions_from_advocate_general.csv')
CSV_LI_CASES = join(DIR_DATA, 'LI_cases.csv')
CSV_CASE_CITATIONS = join(DIR_DATA, 'caselaw_citations.csv')
CSV_LEGISLATION_CITATIONS = join(DIR_DATA, 'legislation_citations.csv')


# TERMINOLOGY DEFINITIONS:

# change here if you want to remap fields (match RS and LI fields)
ECLI = RS_IDENTIFIER = LIDO_SOURCE_ECLI = 'ecli'  # doesn't exist in original LI: generated by script
SOURCE = LI_DOCUMENT_TYPE = 'source'  # doesn't exist in original RS: generated by script
JURISDICTION_COUNTRY = LI_JURISDICTION = 'jurisdiction_country'  # doesn't exist in original RS: generated by script
RS_ISSUED = LI_PUBLICATION_DATE = 'date_published_online'
RS_CREATOR = LI_ISSUING_INSTITUTION = 'instance'
RS_DATE = LI_ENACTMENT_DATE = 'date_judgement'
RS_ZAAKNUMMER = LI_CASE_NUMBER = 'case_number'
RS_SUBJECT = LI_LAW_AREA = 'domains'
RS_HASVERSION = LI_SOURCES = 'alternative_publications'
RS_IDENTIFIER2 = LI_ORIGINAL_URL = 'publication_url'
RS_INHOUDSINDICATIE = LI_SUMMARY = 'summary'
RS_TITLE = LI_TITLE = 'title'
RS_UITSPRAAK = LI_ORIGINAL_URL = 'full_text'


RS_LANGUAGE = 'language'
RS_TYPE = 'document_type'
RS_PROCEDURE = 'procedure_type'
RS_SPATIAL = 'jurisdiction_city'
RS_RELATION = 'predecessor_successor_cases'
RS_REFERENCES = 'referenced_legislation_titles'
RS_INFO = 'info'

RS_DECISION_ECLI = 'decision_ecli'  # generated by script

LI_ID = 'document_id'
LI_DISPLAY_TITLE = 'display_title'
LI_DISPLAY_SUBTITLE = 'display_subtitle'
LI_URL = 'url_to_li'
LI_PUBLICATION_NUMBER = 'publication_number'
LI_ISSUE_NUMBER = 'issue_number'
LI_DATE_ADDED = 'date_added_to_li'
# suffix for li attributes:
LI = '_li'

LIDO_TARGET_ECLI = 'target_ecli'
LIDO_TARGET_ARTICLE = 'target_legislation_url'
LIDO_TARGET_ARTICLE_WEBPAGE = 'target_legislation_article_url'

# map to rename original field names to terminology defined above
# (no need to change: changes automatically if definitions above change):
MAP_RS = {
    'identifier': RS_IDENTIFIER,
    'issued': RS_ISSUED,
    'language': RS_LANGUAGE,
    'creator': RS_CREATOR,
    'date': RS_DATE,
    'zaaknummer': RS_ZAAKNUMMER,
    'type': RS_TYPE,  # 'uitspraak' (decision) or 'conclusie' (opinion)
    'procedure': RS_PROCEDURE,
    'spatial': RS_SPATIAL,
    'subject': RS_SUBJECT,
    'relation': RS_RELATION,  # predecessor and successor cases
    'references': RS_REFERENCES,
    'hasVersion: ': RS_HASVERSION,  # alternative publications
    'identifier2': RS_IDENTIFIER2,
    'title': RS_TITLE,
    'inhoudsindicatie': RS_INHOUDSINDICATIE,
    'info': RS_INFO,
    'uitspraak': RS_UITSPRAAK
}

# original field names of LI can be found here: https://www.legalintelligence.com/files/li-search-endpoint.pdf
MAP_LI = {
    'Id': LI_ID + LI,  # internal id in LI
    'Title': LI_TITLE + LI,
    'DisplayTitle': LI_DISPLAY_TITLE + LI,
    'DisplaySubtitle': LI_DISPLAY_SUBTITLE + LI,
    'Summary': LI_SUMMARY + LI,
    'Url': LI_URL + LI,
    'OriginalUrl': LI_ORIGINAL_URL + LI,
    'Jurisdiction': LI_JURISDICTION + LI,
    'DocumentType': LI_DOCUMENT_TYPE + LI,  # always 'Rechtspraak'
    'LawArea': LI_LAW_AREA + LI,
    'IssuingInstitution': LI_ISSUING_INSTITUTION + LI,
    'CaseNumber': LI_CASE_NUMBER + LI,  # case id (ECLI or whatever was used before)
    'PublicationNumber': LI_PUBLICATION_NUMBER + LI,  # internal document id of publisher
    'IssueNumber': LI_ISSUE_NUMBER + LI,  # collection id of publisher
    'PublicationDate': LI_PUBLICATION_DATE + LI,  # date of document publication
    'EnactmentDate': LI_ENACTMENT_DATE + LI,  # date of uitspraak
    'DateAdded': LI_DATE_ADDED + LI,  # date added to the LI platform
    'Sources': LI_SOURCES + LI  # alternative publishing institutions
}

MAP_CASE_CITATIONS = {
    'source_ecli': LIDO_SOURCE_ECLI,
    'target_ecli': LIDO_TARGET_ECLI,
}

MAP_LEGISLATION_CITATIONS = {
    'source_ecli': LIDO_SOURCE_ECLI,
    'target_article': LIDO_TARGET_ARTICLE,
    'target_article_webpage': LIDO_TARGET_ARTICLE_WEBPAGE
}





