from definitions.terminology.field_values import *

MAP_LI_DOMAINS = {
    'Algemeen': {ALGEMEEN_OVERIG_NIED_GELABELD},
    'Arbeids/Sociaal Recht': {CIVIELRECHT, ARBEIDSRECHT},
    'Bank- en effectenrecht': {ALGEMEEN_OVERIG_NIED_GELABELD, BANK_EN_EFFECTENRECHT},
    'Belastingrecht': {BESTUURSRECHT, BELASTINGRECHT},
    'Bouwrecht': {CIVIELRECHT, VERBINTENISSENRECHT, BOUWRECHT, AANBESTEDINGSRECHT},
    'Buitenlands Recht/Religieus recht': {ALGEMEEN_OVERIG_NIED_GELABELD, BUITENLANDS_RELIGIEUS_RECHT},
    'Burgerlijk recht': {CIVIELRECHT, VERBINTENISSENRECHT, BURGERLIJK_RECHT, GOEDERENRECHT},
    'Burgerlijke rechtsvordering': {CIVIELRECHT, BURGERLIJK_PROCESRECHT},
    'Faillissementsrecht': {CIVIELRECHT, INSOLVENTIERECHT},
    'Gemeenschapsrecht EU': {ALGEMEEN_OVERIG_NIED_GELABELD, GEMEENSCHAPSRECHT_EU},
    'Gezondheidsrecht': {CIVIELRECHT, VERBINTENISSENRECHT, GEZONDHEIDSRECHT, BESTUURSRECHT},
    'Huurrecht/Woonrecht': {CIVIELRECHT, VERBINTENISSENRECHT, HUURRECHT_WOONRECHT, BESTUURSRECHT},
    'Intellectuele eigendom': {CIVIELRECHT, INTELLECTUEEL_EIGENDOMSRECHT},
    'Internationaal Privaatrecht/IPR': {CIVIELRECHT, INTERNATIONAAL_PRIVAATRECHT},
    'Internationaal Publiekrecht (niet EU)': {INTERNATIONAAL_PUBLIEKRECHT},
    'Mededinging': {CIVIELRECHT, BESTUURSRECHT, MEDEDINGINGSRECHT},
    'Nationaliteitsrecht/Vreemdelingenrecht': {BESTUURSRECHT, VREEMDELINGENRECHT},
    'Onbekend': {ALGEMEEN_OVERIG_NIED_GELABELD},
    'Ondernemingsrecht': {CIVIELRECHT, ONDERNEMINGSRECHT},
    'Onderwijs/Studiefinanciering': {BESTUURSRECHT, ONDERWIJS_STUDIEFINANCIERING},
    'Personen- en Familierecht': {CIVIELRECHT, PERSONEN_EN_FAMILIENRECHT},
    'Ruimtelijk Bestuursrecht/Milieurecht/Energierecht': {BESTUURSRECHT, RUIMTELIJK_BESTUURSRECHT_MILIEURECHT_ENERGIERECHT},
    'Staats- en Bestuursrecht': {BESTUURSRECHT},
    'Strafrecht/Strafvordering': {STRAFRECHT},
    'Telecom/ICT/Mediarecht': {CIVIELRECHT, TELECOM_ICT_MEDIARECHT},
    'Verbintenissenrecht': {CIVIELRECHT, VERBINTENISSENRECHT},
    'Vervoer/Verkeersrecht': {CIVIELRECHT, VERBINTENISSENRECHT, VERVOER_VERKEERSRECHT, STRAFRECHT},
    'Verzekeringsrecht': {CIVIELRECHT, VERBINTENISSENRECHT, VERZEKERINGSRECHT}
}

MAP_INSTANCE = {
    "'s-Gravenhage": S_GRAVENHAGE,
    "'s Gravenhage": S_GRAVENHAGE,
    'Den Haag': DEN_HAAG,
    'Sector kanton Rechtbank': SECTOR_KANTON_RECHTBANK,
    'Rechtbank': RECHTBANK
}

MAP_JURISDICTION = {
    'NL': NL,
    'Nederland': NEDERLAND
}

