-- MySQL Script generated by MySQL Workbench
-- Wed Sep  4 13:58:59 2019
-- Mainteiner: Pedro V Hernandez Serrano <p.hernandezserrano@maastrichtuniversity.nl>
-- Model: Case Law    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema caselaw
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema caselaw
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `caselaw` DEFAULT CHARACTER SET utf8 ;
USE `caselaw` ;

-- -----------------------------------------------------
-- Table `caselaw`.`case_related_decision`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `caselaw`.`case_related_decision` ;

CREATE TABLE IF NOT EXISTS `caselaw`.`case_related_decision` (
  `case_ecli` VARCHAR(45) NOT NULL,
  `referencing_case_id` VARCHAR(255) NOT NULL,
  `referenced_case_id` VARCHAR(255) NULL,
  PRIMARY KEY (`case_ecli`));


-- -----------------------------------------------------
-- Table `caselaw`.`case_opinion_from_advocate_general`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `caselaw`.`case_opinion_from_advocate_general` ;

CREATE TABLE IF NOT EXISTS `caselaw`.`case_opinion_from_advocate_general` (
  `case_ecli` VARCHAR(45) NOT NULL,
  `date` DATE NULL,
  `case_number` VARCHAR(255) NULL,
  `description` MEDIUMTEXT NULL,
  `language` VARCHAR(2) NULL,
  `country` VARCHAR(255) NULL,
  `venue` VARCHAR(255) NULL,
  `abstract` VARCHAR(255) NULL,
  `procedure_type` VARCHAR(255) NULL,
  `authority` VARCHAR(255) NULL,
  PRIMARY KEY (`case_ecli`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `caselaw`.`countries`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `caselaw`.`countries` ;

CREATE TABLE IF NOT EXISTS `caselaw`.`countries` (
  `country_id` VARCHAR(2) NOT NULL COMMENT 'Country ISO Code',
  `name` VARCHAR(255) NULL COMMENT 'English name',
  `language` VARCHAR(2) NULL COMMENT 'ISO code for language spoken in country',
  `flag` VARCHAR(255) NULL COMMENT 'Link to image file of flag',
  `eu` BINARY NULL COMMENT 'Part of EU or not?',
  `population` INT NULL COMMENT 'Current / latest population number',
  PRIMARY KEY (`country_id`));


-- -----------------------------------------------------
-- Table `caselaw`.`subjects`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `caselaw`.`subjects` ;

CREATE TABLE IF NOT EXISTS `caselaw`.`subjects` (
  `subject_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `standard_name` VARCHAR(45) NULL,
  PRIMARY KEY (`subject_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `caselaw`.`authorities`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `caselaw`.`authorities` ;

CREATE TABLE IF NOT EXISTS `caselaw`.`authorities` (
  `authority_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `type` VARCHAR(45) NULL,
  `level` VARCHAR(45) NULL,
  `country` VARCHAR(2) NULL,
  `language` VARCHAR(2) NULL,
  `jurisdiction` VARCHAR(45) NULL,
  PRIMARY KEY (`authority_id`),
  UNIQUE INDEX `authority_id_UNIQUE` (`authority_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `caselaw`.`cases`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `caselaw`.`cases` ;

CREATE TABLE IF NOT EXISTS `caselaw`.`cases` (
  `case_id` INT NOT NULL AUTO_INCREMENT,
  `case_ecli` VARCHAR(45) NOT NULL,
  `date` DATE NULL,
  `name` VARCHAR(255) NULL,
  `description` MEDIUMTEXT NULL,
  `language` VARCHAR(2) NULL,
  `venue` VARCHAR(255) NULL,
  `abstract` MEDIUMTEXT NULL,
  `procedure_type` VARCHAR(255) NULL,
  `lodge_date` DATE NULL,
  `link` VARCHAR(255) NULL,
  `country_id` VARCHAR(2) NULL,
  `subject_id` INT NULL,
  `authority_id` INT NULL,
  PRIMARY KEY (`case_id`),
  UNIQUE INDEX `id_UNIQUE` (`case_id` ASC) VISIBLE,
  INDEX `related_decision_idx` (`case_ecli` ASC) VISIBLE,
  INDEX `country_idx` (`country_id` ASC) VISIBLE,
  INDEX `subject_idx` (`subject_id` ASC) VISIBLE,
  INDEX `authority_idx` (`authority_id` ASC) VISIBLE,
  CONSTRAINT `fk_related_decision`
    FOREIGN KEY (`case_ecli`)
    REFERENCES `caselaw`.`case_related_decision` (`case_ecli`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_case_opinion`
    FOREIGN KEY (`case_ecli`)
    REFERENCES `caselaw`.`case_opinion_from_advocate_general` (`case_ecli`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_country`
    FOREIGN KEY (`country_id`)
    REFERENCES `caselaw`.`countries` (`country_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_subject`
    FOREIGN KEY (`subject_id`)
    REFERENCES `caselaw`.`subjects` (`subject_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_authority`
    FOREIGN KEY (`authority_id`)
    REFERENCES `caselaw`.`authorities` (`authority_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `caselaw`.`case_citation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `caselaw`.`case_citation` ;

CREATE TABLE IF NOT EXISTS `caselaw`.`case_citation` (
  `citation_id` INT NOT NULL AUTO_INCREMENT,
  `source_ecli` VARCHAR(45) NOT NULL,
  `source_paragraph` VARCHAR(255) NULL,
  `target_ecli` VARCHAR(45) NOT NULL,
  `target_paragraph` VARCHAR(255) NULL,
  PRIMARY KEY (`citation_id`),
  INDEX `source_case_idx` (`source_ecli` ASC) VISIBLE,
  INDEX `target_case_idx` (`target_ecli` ASC) VISIBLE,
  CONSTRAINT `fk_source_case_cases`
    FOREIGN KEY (`source_ecli`)
    REFERENCES `caselaw`.`cases` (`case_ecli`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_target_case_cases`
    FOREIGN KEY (`target_ecli`)
    REFERENCES `caselaw`.`cases` (`case_ecli`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `caselaw`.`legislation_citation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `caselaw`.`legislation_citation` ;

CREATE TABLE IF NOT EXISTS `caselaw`.`legislation_citation` (
  `citation_id` INT NOT NULL AUTO_INCREMENT,
  `source_ecli` VARCHAR(45) NOT NULL,
  `source_paragraph` VARCHAR(255) NULL,
  `target_id` VARCHAR(255) NOT NULL,
  `target_paragraph` VARCHAR(255) NULL,
  `target_name` VARCHAR(255) NULL,
  `target_sourcename` VARCHAR(255) NULL,
  `target_link` VARCHAR(255) NULL,
  PRIMARY KEY (`citation_id`),
  UNIQUE INDEX `citation_id_UNIQUE` (`citation_id` ASC) VISIBLE,
  INDEX `source_case_idx` (`source_ecli` ASC) VISIBLE,
  CONSTRAINT `fk_source_case_legislation`
    FOREIGN KEY (`source_ecli`)
    REFERENCES `caselaw`.`cases` (`case_ecli`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
