-- MySQL Script generated by MySQL Workbench
-- Mon Mar 30 18:25:15 2020
-- Mainteiner: Pedro V Hernandez Serrano <p.hernandezserrano@maastrichtuniversity.nl>
-- Model: Case Law    Version: 6.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema caselaw
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema caselaw
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `caselaw` DEFAULT CHARACTER SET utf8 ;
USE `caselaw` ;

-- -----------------------------------------------------
-- Table `caselaw`.`court`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `caselaw`.`court` ;

CREATE TABLE IF NOT EXISTS `caselaw`.`court` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL COMMENT 'Official English name for the court or authority or legal body',
  `type` VARCHAR(45) NULL COMMENT 'Classification of the court into exactly one of these categories: \n\n- Court of Justice of the EU (CJEU)\n- European Court of Human Rights (ECHR)\n- General Court (GC)\n- A particular national court (N)',
  `level` VARCHAR(45) NULL COMMENT 'Classification of the level of authority of the court into exactly one of these categories:\n\n- EU (In the case of CJEU, ECHR or GC)\n- Supreme (Supreme court of the particular country)\n- Lower (Lower courts)',
  `country` VARCHAR(2) NULL COMMENT 'The ISO code for the country or region in which this court is legally situated',
  `language` VARCHAR(2) NULL COMMENT 'The primary language of the court\'s decisions',
  `jurisdiction` VARCHAR(45) NULL COMMENT 'Area of jurisdiction of this court',
  `law_area` VARCHAR(45) NULL COMMENT 'Legal issues or topics that this court arbitrates',
  `authority_level` VARCHAR(45) NULL COMMENT 'A measure the level of authority of a national court: n/m\n\nwhere m is the number of distinct levels of courts in the particular country\nand n is the level of this particular court in the hierarchy of that country',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `caselaw`.`case`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `caselaw`.`case` ;

CREATE TABLE IF NOT EXISTS `caselaw`.`case` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date` DATE NULL COMMENT 'The date on which the court decision was first published',
  `name` VARCHAR(255) NULL COMMENT 'The official title of the court decision (e.g. Kramer vs. Kramer)',
  `description` MEDIUMTEXT NULL COMMENT 'A short summary or description of the court decision proceedings and outcome',
  `language` VARCHAR(2) NULL COMMENT 'The primary language of the first published decision text',
  `venue` VARCHAR(255) NULL COMMENT 'The name of the physical location in which the decision was made i.e., name of city, town or district etc.',
  `abstract` MEDIUMTEXT NULL COMMENT 'Official summary of the case',
  `procedure_type` VARCHAR(255) NULL COMMENT 'Type of legal procedure or ruling (e.g. reference for preliminary ruling)',
  `lodge_date` DATE NULL COMMENT 'The date on which the applicant lodged or opened the case',
  `link` VARCHAR(255) NULL COMMENT 'Publicly accessible HTTP URL to an official webpage which contains more metadata about the case and / or the full text of the decision',
  `ecli` VARCHAR(60) NOT NULL,
  `court_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_case_court_idx` (`court_id` ASC) VISIBLE,
  UNIQUE INDEX `ecli_UNIQUE` (`ecli` ASC) VISIBLE,
  CONSTRAINT `fk_case_court`
    FOREIGN KEY (`court_id`)
    REFERENCES `caselaw`.`court` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `caselaw`.`subject`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `caselaw`.`subject` ;

CREATE TABLE IF NOT EXISTS `caselaw`.`subject` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL COMMENT 'An English name for the legal topic (subject)',
  `standard_name` VARCHAR(45) NULL COMMENT 'A standardized name for the legal topic (commonly used across legal systems or jurisdictions)',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `caselaw`.`case_citation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `caselaw`.`case_citation` ;

CREATE TABLE IF NOT EXISTS `caselaw`.`case_citation` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `source_ecli` VARCHAR(255) NULL COMMENT 'ECLI number for the citing case',
  `source_paragraph` VARCHAR(255) NULL COMMENT 'The paragraph number from the source case which is citing another case (the citor) ',
  `target_ecli` VARCHAR(255) NULL COMMENT 'ECLI number for the cited case',
  `target_paragraph` VARCHAR(255) NULL COMMENT 'The paragraph number which is cited from the the cited case (the citee)',
  `case_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `idx_case_citation_citation` (`case_id` ASC) VISIBLE,
  CONSTRAINT `fk_case_citation_citation`
    FOREIGN KEY (`case_id`)
    REFERENCES `caselaw`.`case` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `caselaw`.`legislation_citation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `caselaw`.`legislation_citation` ;

CREATE TABLE IF NOT EXISTS `caselaw`.`legislation_citation` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `source_paragraph` VARCHAR(255) NULL COMMENT 'The paragraph number from the source case which is citing a piece of legislation (the citor) ',
  `target_id` VARCHAR(255) NULL,
  `target_paragraph` VARCHAR(255) NULL COMMENT 'The paragraph number from the legislation which is cited (the citee) ',
  `target_name` VARCHAR(255) NULL COMMENT 'The official name of the piece of legislation (e.g. Article x.xx on Crime & Punishment)',
  `target_sourcename` VARCHAR(255) NULL COMMENT 'The name of the legal source from which the cited legislation originates (e.g. Book, Article etc.)',
  `target_link` VARCHAR(255) NULL COMMENT 'Publicly accessible HTTP URLto an official webpage which contains the text for the cited legislation',
  `case_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `idx_legislation_citation_case` (`case_id` ASC) VISIBLE,
  CONSTRAINT `fk_legislation_citation_case`
    FOREIGN KEY (`case_id`)
    REFERENCES `caselaw`.`case` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `caselaw`.`country`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `caselaw`.`country` ;

CREATE TABLE IF NOT EXISTS `caselaw`.`country` (
  `id` VARCHAR(3) NOT NULL,
  `name` VARCHAR(255) NULL COMMENT 'A human-readable full name of the country in English',
  `language` VARCHAR(2) NULL COMMENT 'The International Organization for Standardization (ISO) code for the main official language of the country',
  `flag` VARCHAR(255) NULL COMMENT 'An http link to an image file depicting the current national flag for the country',
  `eu` BINARY NULL COMMENT 'Is this country part of the European Union (EU)?',
  `eea` BINARY NULL COMMENT 'Is this country part of the European Economic Area (EEA) countries?',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `caselaw`.`case_opinion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `caselaw`.`case_opinion` ;

CREATE TABLE IF NOT EXISTS `caselaw`.`case_opinion` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'The originating EU country of the case',
  `ecli` VARCHAR(60) NOT NULL COMMENT 'The European Case Law Identifier (ECLI) for the case being opined',
  `date` DATE NULL COMMENT 'The date on which this opinion on the case from the advocate general was published',
  `case_number` VARCHAR(255) NULL COMMENT 'The case number of the case which is being opined',
  `description` MEDIUMTEXT NULL COMMENT 'a description or summary of the opinion',
  `language` VARCHAR(2) NULL COMMENT 'The ISO code of the language in which the opinion is expressed',
  `country` VARCHAR(255) NULL COMMENT 'The country from which the opinion emerged',
  `venue` VARCHAR(255) NULL COMMENT 'The name of the physical location (city, town, district etc.) in which the opinion was first stated',
  `abstract` VARCHAR(255) NULL COMMENT 'An English summary of the opinion',
  `procedure_type` VARCHAR(255) NULL COMMENT 'The type of legal procedure (e.g. reference for preliminary ruling) for the case being opined',
  `authority` VARCHAR(255) NULL COMMENT 'The English name of the court which is arbitrating the case being opined',
  PRIMARY KEY (`id`),
  INDEX `fk_case_opinion_case_idx` (`ecli` ASC) VISIBLE,
  UNIQUE INDEX `ecli_UNIQUE` (`ecli` ASC) VISIBLE,
  CONSTRAINT `fk_case_opinion_case`
    FOREIGN KEY (`ecli`)
    REFERENCES `caselaw`.`case` (`ecli`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `caselaw`.`case_related_decision`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `caselaw`.`case_related_decision` ;

CREATE TABLE IF NOT EXISTS `caselaw`.`case_related_decision` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `referencing_case_ecli` VARCHAR(255) NULL COMMENT 'Case which references another one because it is related or similar (not just via an official or explicit citation)',
  `referenced_case_ecli` VARCHAR(255) NULL COMMENT 'Case which is referenced by another one because it is related or similar (not just via an official or explicit citation)',
  `case_id` INT NOT NULL,
  `case_id1` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_case_related_decision_case1_idx` (`case_id1` ASC) VISIBLE,
  CONSTRAINT `fk_case_related_decision_case1`
    FOREIGN KEY (`case_id1`)
    REFERENCES `caselaw`.`case` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `caselaw`.`legal_intelligence_case`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `caselaw`.`legal_intelligence_case` ;

CREATE TABLE IF NOT EXISTS `caselaw`.`legal_intelligence_case` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ecli` VARCHAR(255) NOT NULL,
  `name` VARCHAR(255) NULL COMMENT 'The official title of the court decision (e.g. Kramer vs. Kramer)',
  `date` DATE NULL,
  `abstract` MEDIUMTEXT NULL COMMENT 'Official summary of the case',
  `subject` VARCHAR(255) NULL,
  `link` VARCHAR(45) NULL,
  `DisplayTitle` VARCHAR(255) NULL,
  `OriginalUrl` VARCHAR(255) NULL,
  `Jurisidiction` VARCHAR(255) NULL,
  `DocumentType` VARCHAR(255) NULL,
  `CaseNumber` VARCHAR(255) NULL,
  `PublicationNumber` VARCHAR(255) NULL,
  `IssueNumber` VARCHAR(255) NULL,
  `lodge_date` DATE NULL,
  `DateAdded` DATE NULL,
  `Sources` VARCHAR(255) NULL,
  `UrlWithAutoLogOnToken` VARCHAR(255) NULL,
  `court` VARCHAR(255) NULL,
  `DisplaySubtitle` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  INDEX `idx_licase_case` (`ecli` ASC) VISIBLE,
  UNIQUE INDEX `ecli_UNIQUE` (`ecli` ASC) VISIBLE,
  CONSTRAINT `fk_licase_case`
    FOREIGN KEY (`ecli`)
    REFERENCES `caselaw`.`case` (`ecli`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `caselaw`.`case_subject`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `caselaw`.`case_subject` ;

CREATE TABLE IF NOT EXISTS `caselaw`.`case_subject` (
  `case_id` INT NOT NULL,
  `subject_id` INT NOT NULL,
  PRIMARY KEY (`case_id`, `subject_id`),
  INDEX `idx_subject` (`subject_id` ASC) VISIBLE,
  CONSTRAINT `fk_case_subject_case`
    FOREIGN KEY (`case_id`)
    REFERENCES `caselaw`.`case` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_case_subject_subject`
    FOREIGN KEY (`subject_id`)
    REFERENCES `caselaw`.`subject` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `caselaw`.`case_country`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `caselaw`.`case_country` ;

CREATE TABLE IF NOT EXISTS `caselaw`.`case_country` (
  `case_id` INT NOT NULL,
  `country_id` VARCHAR(3) NOT NULL,
  PRIMARY KEY (`country_id`, `case_id`),
  INDEX `idx_country` (`country_id` ASC) VISIBLE,
  CONSTRAINT `fk_case_coutry_country`
    FOREIGN KEY (`country_id`)
    REFERENCES `caselaw`.`country` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_case_country_case`
    FOREIGN KEY (`case_id`)
    REFERENCES `caselaw`.`case` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
