-- MySQL Script generated by MySQL Workbench
-- Wed Aug 14 15:44:20 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema caselaw
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema caselaw
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `caselaw` DEFAULT CHARACTER SET utf8 ;
USE `caselaw` ;

-- -----------------------------------------------------
-- Table `caselaw`.`Subject`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `caselaw`.`Subject` (
  `SubjectId` INT NOT NULL,
  `Resource Identifier` VARCHAR(45) NULL,
  `Text_nl` VARCHAR(45) NULL,
  `Text_en` VARCHAR(45) NULL,
  PRIMARY KEY (`SubjectId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `caselaw`.`Creator`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `caselaw`.`Creator` (
  `CreatorId` INT NOT NULL,
  `Resource Identifier` VARCHAR(45) NULL,
  `Text_nl` VARCHAR(45) NULL,
  `Text_en` VARCHAR(45) NULL,
  PRIMARY KEY (`CreatorId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `caselaw`.`CaseCitation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `caselaw`.`CaseCitation` (
  `CitationId` INT NOT NULL,
  `ECLIsource` VARCHAR(45) NULL,
  `ParagraphSource` VARCHAR(45) NULL,
  `ECLItarget` VARCHAR(45) NULL,
  `ParagraphTarget` VARCHAR(45) NULL,
  PRIMARY KEY (`CitationId`),
  INDEX `ECLIsource_idx` (`ECLIsource` ASC) VISIBLE,
  CONSTRAINT `ECLIsource`
    FOREIGN KEY (`ECLIsource`)
    REFERENCES `caselaw`.`Case` (`ECLI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `caselaw`.`Legislation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `caselaw`.`Legislation` (
  `LegislationId` INT NOT NULL,
  `Title` VARCHAR(45) NULL,
  `Resource Identifier` VARCHAR(45) NULL,
  `Type` VARCHAR(45) NULL,
  PRIMARY KEY (`LegislationId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `caselaw`.`LegislationCitation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `caselaw`.`LegislationCitation` (
  `CitationId` INT NOT NULL,
  `ECLISource` VARCHAR(45) NULL,
  `ParagraphSource` VARCHAR(45) NULL,
  `LegislationTargetId` INT NULL,
  PRIMARY KEY (`CitationId`),
  INDEX `LegislationTargetId_idx` (`LegislationTargetId` ASC) VISIBLE,
  CONSTRAINT `LegislationTargetId`
    FOREIGN KEY (`LegislationTargetId`)
    REFERENCES `caselaw`.`Legislation` (`LegislationId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `caselaw`.`Case`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `caselaw`.`Case` (
  `ECLI` VARCHAR(45) NOT NULL,
  `Title` VARCHAR(45) NULL,
  `Date(Uitspraaldatum)` DATE NULL,
  `Issued(Publicatiedatum)` DATE NULL,
  `Case number (Zaaknummer)` VARCHAR(45) NULL,
  `Description(Uitspraak)` LONGTEXT NULL,
  `Version` VARCHAR(45) NULL,
  `Casecol` VARCHAR(45) NULL,
  `SubjectId` INT NULL,
  `CitationId` INT NULL,
  `CreatorId` INT NULL,
  `Locations(list)` VARCHAR(45) NULL,
  `LocationsCount` INT NULL,
  `LegislationCitationId` INT NULL,
  PRIMARY KEY (`ECLI`),
  INDEX `SubjectId_idx` (`SubjectId` ASC) VISIBLE,
  INDEX `CreatorId_idx` (`CreatorId` ASC) VISIBLE,
  INDEX `CitationId_idx` (`CitationId` ASC) VISIBLE,
  INDEX `LegilsationCitationId_idx` (`LegislationCitationId` ASC) VISIBLE,
  CONSTRAINT `SubjectId`
    FOREIGN KEY (`SubjectId`)
    REFERENCES `caselaw`.`Subject` (`SubjectId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `CreatorId`
    FOREIGN KEY (`CreatorId`)
    REFERENCES `caselaw`.`Creator` (`CreatorId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `CitationId`
    FOREIGN KEY (`CitationId`)
    REFERENCES `caselaw`.`CaseCitation` (`CitationId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `LegilsationCitationId`
    FOREIGN KEY (`LegislationCitationId`)
    REFERENCES `caselaw`.`LegislationCitation` (`CitationId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
